import {
  UserProfile,
  Lead,
  Admission,
  Student,
  Course,
  CourseModule,
  Lesson,
  LessonProgress,
  Batch,
  BatchTransferAudit,
  ClassSession,
  AttendanceRecord,
  Assignment,
  AssignmentSubmission,
  Quiz,
  QuizQuestion,
  QuizAttempt,
  StudentFeeAccount,
  Installment,
  Payment,
  Receipt,
  Expense,
  Vendor,
  PlacementProfile,
  JobOpening,
  JobApplication,
  Certificate,
  NotificationItem,
  AuditLog,
  SystemSettings,
  SapServerSystem,
  SapServerAllocation,
  StudentDoubt,
  DoubtMessage,
  MeetingParticipantLog,
} from '@/types';
import { persistentStorage } from './persistent-storage-adapter';
import { calculateGstBreakdown } from './gst-service';

// In-Memory initial seed data with durable filesystem persistence & Supabase Postgres bridge
class InstituteDataStore {
  constructor() {
    this.hydrateFromDisk();
  }

  public hydrateFromDisk(): boolean {
    try {
      const snapshot = persistentStorage.loadState();
      if (snapshot) {
        if (snapshot.settings) this.settings = snapshot.settings;
        if (snapshot.users?.length) this.users = snapshot.users;
        if (snapshot.admissions?.length) this.admissions = snapshot.admissions;
        if (snapshot.students?.length) this.students = snapshot.students;
        if (snapshot.leads?.length) this.leads = snapshot.leads;
        if (snapshot.courses?.length) this.courses = snapshot.courses;
        if (snapshot.modules?.length) this.modules = snapshot.modules;
        if (snapshot.lessons?.length) this.lessons = snapshot.lessons;
        if (snapshot.lessonProgress?.length) this.lessonProgress = snapshot.lessonProgress;
        if (snapshot.batches?.length) this.batches = snapshot.batches;
        if (snapshot.batchTransferAudits?.length) this.batchTransferAudits = snapshot.batchTransferAudits;
        if (snapshot.classSessions?.length) this.classSessions = snapshot.classSessions;
        if (snapshot.attendanceRecords?.length) this.attendanceRecords = snapshot.attendanceRecords;
        if (snapshot.assignments?.length) this.assignments = snapshot.assignments;
        if (snapshot.submissions?.length) this.submissions = snapshot.submissions;
        if (snapshot.quizzes?.length) this.quizzes = snapshot.quizzes;
        if (snapshot.quizQuestions?.length) this.quizQuestions = snapshot.quizQuestions;
        if (snapshot.quizAttempts?.length) this.quizAttempts = snapshot.quizAttempts;
        if (snapshot.feeAccounts?.length) this.feeAccounts = snapshot.feeAccounts;
        if (snapshot.installments?.length) this.installments = snapshot.installments;
        if (snapshot.payments?.length) this.payments = snapshot.payments;
        if (snapshot.receipts?.length) {
          this.receipts = snapshot.receipts;
          if (!this.receipts.some((r) => r.id === 'rcpt-03')) {
            this.receipts.push({
              id: 'rcpt-03',
              receipt_number: 'REC-2026-0003',
              payment_id: 'pay-03',
              student_id: 'stu-02',
              student_name: 'Sneha Kulkarni',
              admission_number: 'ADM-2026-0002',
              course_name: 'SAP S/4HANA Materials Management (MM)',
              payment_amount: 20000,
              payment_mode: 'UPI',
              transaction_reference: 'UPI/260202/882194',
              payment_date: '2026-02-02',
              remaining_balance: 20000,
              authorized_by: 'Suresh Kumar (Chief Accountant)',
              institute_name: 'Next-Gen ERP Solutions',
              institute_address: 'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad 500081',
              institute_phone: '+91 98765 43210',
              institute_gst: '36AAACN1234F1Z8',
              supply_type: 'INTER_STATE',
              place_of_supply: 'Maharashtra (27)',
              place_of_supply_code: '27',
              sac_code: '999293',
              taxable_amount: 16949.15,
              cgst_rate: 0,
              cgst_amount: 0,
              sgst_rate: 0,
              sgst_amount: 0,
              igst_rate: 18,
              igst_amount: 3050.85,
              total_tax: 3050.85,
              is_reverse_charge: false,
              irn: 'b7c2d34568fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b777',
              ack_no: '1226102948393',
              ack_date: '2026-02-02T11:20:00Z',
              created_at: '2026-02-02T11:20:00Z',
            });
          }

          // Self-healing auto-enrichment: ensure all receipts maintain full GST breakdown & e-invoice IRN
          for (let i = 0; i < this.receipts.length; i++) {
            const r = this.receipts[i];
            if (!r.supply_type || r.taxable_amount === undefined || !r.irn) {
              const stu = (this.students || []).find((s) => s.id === r.student_id);
              const adm = (this.admissions || []).find(
                (a) => a.admission_number === r.admission_number || (stu && a.id === stu.admission_id)
              );
              const studentLoc =
                stu?.state_code ||
                stu?.state ||
                adm?.state_code ||
                adm?.state ||
                r.place_of_supply_code ||
                r.place_of_supply ||
                stu?.address ||
                adm?.city ||
                adm?.address;

              const breakdown = calculateGstBreakdown(r.payment_amount, studentLoc, {
                customDocNumber: r.receipt_number || `REC-${r.id}`,
                customDocDate:
                  r.payment_date ||
                  r.created_at?.split('T')[0] ||
                  new Date().toISOString().split('T')[0],
                instituteGstin: this.settings?.gst_number || '36AAACN1234F1Z8',
                instituteStateCode: '36',
              });

              this.receipts[i] = {
                ...r,
                institute_name: r.institute_name || this.settings?.institute_name || 'Next-Gen ERP Solutions',
                institute_address:
                  r.institute_address ||
                  this.settings?.address ||
                  'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad 500081',
                institute_phone: r.institute_phone || this.settings?.phone || '+91 98765 43210',
                institute_gst: r.institute_gst || this.settings?.gst_number || '36AAACN1234F1Z8',
                supply_type: r.supply_type || breakdown.supply_type,
                place_of_supply: r.place_of_supply || breakdown.place_of_supply,
                place_of_supply_code: r.place_of_supply_code || breakdown.place_of_supply_code,
                sac_code: r.sac_code || breakdown.sac_code,
                taxable_amount: r.taxable_amount ?? breakdown.taxable_amount,
                cgst_rate: r.cgst_rate ?? breakdown.cgst_rate,
                cgst_amount: r.cgst_amount ?? breakdown.cgst_amount,
                sgst_rate: r.sgst_rate ?? breakdown.sgst_rate,
                sgst_amount: r.sgst_amount ?? breakdown.sgst_amount,
                igst_rate: r.igst_rate ?? breakdown.igst_rate,
                igst_amount: r.igst_amount ?? breakdown.igst_amount,
                total_tax: r.total_tax ?? breakdown.total_tax,
                is_reverse_charge: r.is_reverse_charge ?? false,
                irn: r.irn || breakdown.irn,
                ack_no: r.ack_no || breakdown.ack_no,
                ack_date: r.ack_date || breakdown.ack_date,
              };
            }
          }
        }
        if (snapshot.expenses?.length) this.expenses = snapshot.expenses;
        if (snapshot.vendors?.length) this.vendors = snapshot.vendors;
        if (snapshot.placementProfiles?.length) this.placementProfiles = snapshot.placementProfiles;
        if (snapshot.jobOpenings?.length) this.jobOpenings = snapshot.jobOpenings;
        if (snapshot.jobApplications?.length) this.jobApplications = snapshot.jobApplications;
        if (snapshot.certificates?.length) this.certificates = snapshot.certificates;
        if (snapshot.notifications?.length) this.notifications = snapshot.notifications;
        if (snapshot.auditLogs?.length) this.auditLogs = snapshot.auditLogs;
        if (snapshot.sapSystems?.length) this.sapSystems = snapshot.sapSystems;
        else if (snapshot.sapServers?.length) this.sapSystems = snapshot.sapServers;
        if (snapshot.sapAllocations?.length) this.sapAllocations = snapshot.sapAllocations;
        if (snapshot.doubts?.length) this.doubts = snapshot.doubts;
        if (snapshot.meetingLogs?.length) this.meetingLogs = snapshot.meetingLogs;
        return true;
      }
    } catch (err) {
      console.warn('[InstituteDataStore] Error hydrating from disk, using seed defaults:', err);
    }
    return false;
  }

  public persist(): void {
    persistentStorage.scheduleSave(this);
  }

  public persistSync(): boolean {
    return persistentStorage.saveState(this);
  }
  public settings: SystemSettings = {
    id: 'sys-01',
    institute_name: 'Next-Gen ERP Solutions',
    tagline: 'Premier SAP Training, Certification & Placement Institute',
    address: 'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad, Telangana 500081',
    phone: '+91 98765 43210',
    email: 'admissions@next-generpsolutions.com',
    gst_number: '36AAACN1234F1Z8',
    default_currency: 'INR',
    academic_year: '2026-2027',
    receipt_prefix: 'REC',
    invoice_prefix: 'INV',
    timezone: 'Asia/Kolkata',
    enable_email_notifications: true,
    enable_sms_notifications: false,
    enable_whatsapp_notifications: true,
  };

  public users: UserProfile[] = [
    {
      id: 'usr-superadmin',
      email: 'superadmin@next-generpsolutions.com',
      full_name: 'Rajesh Sharma (Director)',
      role: 'super_admin',
      phone: '+91 98000 00001',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-admin',
      email: 'admin@next-generpsolutions.com',
      full_name: 'Priya Nair (Operations Head)',
      role: 'admin',
      phone: '+91 98000 00002',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-accounts',
      email: 'accounts@next-generpsolutions.com',
      full_name: 'Suresh Kumar (Chief Accountant)',
      role: 'accountant',
      phone: '+91 98000 00003',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-counsellor',
      email: 'counsellor@next-generpsolutions.com',
      full_name: 'Ananya Desai (Senior Counsellor)',
      role: 'counsellor',
      phone: '+91 98000 00004',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-trainer-fico',
      email: 'vikram.fico@next-generpsolutions.com',
      full_name: 'Vikram Rao (SAP FICO Lead)',
      role: 'trainer',
      phone: '+91 98000 00005',
      is_active: true,
      assigned_course_ids: ['crs-fico-01'],
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-trainer-mm',
      email: 'neha.mm@next-generpsolutions.com',
      full_name: 'Neha Patel (SAP MM Lead)',
      role: 'trainer',
      phone: '+91 98000 00006',
      is_active: true,
      assigned_course_ids: ['crs-mm-01'],
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-placement',
      email: 'placement@next-generpsolutions.com',
      full_name: 'Sunita Reddy (Placement Head)',
      role: 'placement_coordinator',
      phone: '+91 98000 00007',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-support-01',
      email: 'support@next-generpsolutions.com',
      full_name: 'Ananya Deshmukh (SAP Support Lead)',
      role: 'support',
      phone: '+91 98000 00008',
      is_active: true,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'usr-student-01',
      email: 'amit.gupta@student.next-gen.com',
      full_name: 'Amit Gupta',
      role: 'student',
      phone: '+91 98111 22233',
      is_active: true,
      created_at: '2026-01-25T00:00:00Z',
      updated_at: '2026-01-25T00:00:00Z',
    },
    {
      id: 'usr-student-02',
      email: 'sneha.k@student.next-gen.com',
      full_name: 'Sneha Kulkarni',
      role: 'student',
      phone: '+91 98222 33344',
      is_active: true,
      created_at: '2026-02-02T00:00:00Z',
      updated_at: '2026-02-02T00:00:00Z',
    },
  ];

  public courses: Course[] = [
    {
      id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      course_code: 'SAP-FICO-2026',
      description: 'Comprehensive Financial Accounting and Controlling on SAP S/4HANA with live enterprise implementation scenarios and S/4HANA migration projects.',
      duration_weeks: 12,
      category: 'SAP Functional',
      trainer_id: 'usr-trainer-fico',
      trainer_name: 'Vikram Rao (SAP FICO Lead)',
      price: 45000,
      status: 'Published',
      modules_count: 3,
      lessons_count: 5,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      course_code: 'SAP-MM-2026',
      description: 'End-to-end Procurement, Inventory Management, Logistics Invoice Verification (LIV), and Master Data Governance (MDG).',
      duration_weeks: 10,
      category: 'SAP Functional',
      trainer_id: 'usr-trainer-mm',
      trainer_name: 'Neha Patel (SAP MM Lead)',
      price: 40000,
      status: 'Published',
      modules_count: 2,
      lessons_count: 4,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'crs-sd-01',
      course_name: 'SAP Sales & Distribution (SD)',
      course_code: 'SAP-SD-2026',
      description: 'Order-to-Cash (O2C) cycle, Pricing Procedures, Shipping, Credit Management, and S/4HANA Sales integration.',
      duration_weeks: 10,
      category: 'SAP Functional',
      price: 40000,
      status: 'Published',
      modules_count: 2,
      lessons_count: 3,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'crs-abap-01',
      course_name: 'SAP ABAP on HANA & RESTful Application Programming (RAP)',
      course_code: 'SAP-ABAP-2026',
      description: 'Modern ABAP 7.5+, Core Data Services (CDS Views), AMDP, OData services, SAP Fiori elements, and RAP architecture.',
      duration_weeks: 12,
      category: 'SAP Technical',
      price: 50000,
      status: 'Published',
      modules_count: 3,
      lessons_count: 6,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
  ];

  public modules: CourseModule[] = [
    {
      id: 'mod-fico-01',
      course_id: 'crs-fico-01',
      title: 'Module 1: Enterprise Structure & General Ledger',
      description: 'Company Code, Chart of Accounts, Fiscal Year Variants, and Document Posting',
      order_index: 1,
      lessons_count: 3,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'mod-fico-02',
      course_id: 'crs-fico-01',
      title: 'Module 2: Accounts Payable & Accounts Receivable',
      description: 'Vendor/Customer Master, Automatic Payment Program (F110), and Dunning',
      order_index: 2,
      lessons_count: 2,
      created_at: '2026-01-05T00:00:00Z',
      updated_at: '2026-01-05T00:00:00Z',
    },
  ];

  public lessons: Lesson[] = [
    {
      id: 'les-fico-101',
      module_id: 'mod-fico-01',
      course_id: 'crs-fico-01',
      title: '1.1 Introduction to SAP S/4HANA Architecture & Navigation',
      lesson_type: 'Video',
      duration_minutes: 45,
      order_index: 1,
      is_published: true,
      content_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
      text_content: 'SAP S/4HANA represents the next-generation ERP suite. Key changes include in-memory computing, Universal Journal (ACDOCA), and real-time financial reporting.',
      created_at: '2026-01-06T00:00:00Z',
      updated_at: '2026-01-06T00:00:00Z',
    },
    {
      id: 'les-fico-102',
      module_id: 'mod-fico-01',
      course_id: 'crs-fico-01',
      title: '1.2 Configuring Enterprise Structure (OX02, OX15, OX16)',
      lesson_type: 'Video',
      duration_minutes: 60,
      order_index: 2,
      is_published: true,
      content_url: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
      text_content: 'Step-by-step configuration of Company, Company Code, Credit Control Area, and assignments.',
      created_at: '2026-01-06T00:00:00Z',
      updated_at: '2026-01-06T00:00:00Z',
    },
    {
      id: 'les-fico-103',
      module_id: 'mod-fico-01',
      course_id: 'crs-fico-01',
      title: 'Module 1 Blueprint Handout & Configuration Guide',
      lesson_type: 'PDF',
      duration_minutes: 20,
      order_index: 3,
      is_published: true,
      content_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      text_content: 'Comprehensive PDF reference documentation for Enterprise Structure setup.',
      created_at: '2026-01-06T00:00:00Z',
      updated_at: '2026-01-06T00:00:00Z',
    },
    {
      id: 'les-fico-201',
      module_id: 'mod-fico-02',
      course_id: 'crs-fico-01',
      title: '2.1 Business Partner (BP) Approach in S/4HANA',
      lesson_type: 'Video',
      duration_minutes: 55,
      order_index: 1,
      is_published: true,
      content_url: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
      created_at: '2026-01-07T00:00:00Z',
      updated_at: '2026-01-07T00:00:00Z',
    },
    {
      id: 'les-fico-202',
      module_id: 'mod-fico-02',
      course_id: 'crs-fico-01',
      title: '2.2 Automatic Payment Program (F110) End-to-End',
      lesson_type: 'Video',
      duration_minutes: 75,
      order_index: 2,
      is_published: true,
      content_url: 'https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,960x540_1000,1280x720_1500,1920x1080_2500,.mp4.csmil/master.m3u8',
      created_at: '2026-01-07T00:00:00Z',
      updated_at: '2026-01-07T00:00:00Z',
    },
  ];

  public lessonProgress: LessonProgress[] = [
    {
      id: 'lp-01',
      student_id: 'stu-01',
      course_id: 'crs-fico-01',
      lesson_id: 'les-fico-101',
      last_watched_seconds: 2700,
      video_total_seconds: 2700,
      completed_percentage: 100,
      is_completed: true,
      completion_date: '2026-02-05T10:00:00Z',
      updated_at: '2026-02-05T10:00:00Z',
    },
    {
      id: 'lp-02',
      student_id: 'stu-01',
      course_id: 'crs-fico-01',
      lesson_id: 'les-fico-102',
      last_watched_seconds: 3600,
      video_total_seconds: 3600,
      completed_percentage: 100,
      is_completed: true,
      completion_date: '2026-02-07T11:00:00Z',
      updated_at: '2026-02-07T11:00:00Z',
    },
    {
      id: 'lp-03',
      student_id: 'stu-01',
      course_id: 'crs-fico-01',
      lesson_id: 'les-fico-201',
      last_watched_seconds: 1200,
      video_total_seconds: 3300,
      completed_percentage: 36.3,
      is_completed: false,
      updated_at: '2026-02-12T14:30:00Z',
    },
  ];

  public batches: Batch[] = [
    {
      id: 'batch-fico-01',
      batch_code: 'B-FICO-2601',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      trainer_id: 'usr-trainer-fico',
      trainer_name: 'Vikram Rao (SAP FICO Lead)',
      training_mode: 'Hybrid',
      start_date: '2026-02-01',
      end_date: '2026-04-30',
      start_time: '08:00',
      end_time: '10:00',
      days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      maximum_capacity: 25,
      current_enrolled: 18,
      status: 'Active',
      created_at: '2026-01-15T00:00:00Z',
      updated_at: '2026-01-15T00:00:00Z',
    },
    {
      id: 'batch-mm-01',
      batch_code: 'B-MM-2601',
      batch_name: 'SAP MM Weekend Professional Batch',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      trainer_id: 'usr-trainer-mm',
      trainer_name: 'Neha Patel (SAP MM Lead)',
      training_mode: 'Online',
      start_date: '2026-02-15',
      end_date: '2026-05-15',
      start_time: '10:00',
      end_time: '13:00',
      days: ['Sat', 'Sun'],
      maximum_capacity: 30,
      current_enrolled: 22,
      status: 'Active',
      created_at: '2026-01-15T00:00:00Z',
      updated_at: '2026-01-15T00:00:00Z',
    },
  ];

  public batchTransferAudits: BatchTransferAudit[] = [];

  public admissions: Admission[] = [
    {
      id: 'adm-01',
      admission_number: 'ADM-2026-0001',
      student_name: 'Amit Gupta',
      phone: '+91 98111 22233',
      email: 'amit.gupta@student.next-gen.com',
      dob: '1999-05-14',
      gender: 'Male',
      address: 'H-12, Madhapur',
      city: 'Hyderabad',
      education: 'B.Com, MBA Finance',
      experience_years: 2,
      current_employment_status: 'Employed',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      training_mode: 'Hybrid',
      batch_id: 'batch-fico-01',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      trainer_id: 'usr-trainer-fico',
      trainer_name: 'Vikram Rao',
      admission_date: '2026-01-25',
      course_fee: 45000,
      discount: 5000,
      discount_reason: 'Early bird registration discount',
      net_payable: 40000,
      payment_plan: '3 Installments',
      counsellor_id: 'usr-counsellor',
      counsellor_name: 'Ananya Desai',
      status: 'Confirmed',
      created_at: '2026-01-25T10:00:00Z',
      updated_at: '2026-01-25T10:00:00Z',
    },
    {
      id: 'adm-02',
      admission_number: 'ADM-2026-0002',
      student_name: 'Sneha Kulkarni',
      phone: '+91 98222 33344',
      email: 'sneha.k@student.next-gen.com',
      dob: '2001-08-20',
      gender: 'Female',
      address: '404 Baner Road',
      city: 'Pune',
      education: 'B.Tech Mechanical',
      experience_years: 1,
      current_employment_status: 'Career Gap',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      training_mode: 'Online',
      batch_id: 'batch-mm-01',
      batch_name: 'SAP MM Weekend Professional Batch',
      trainer_id: 'usr-trainer-mm',
      trainer_name: 'Neha Patel',
      admission_date: '2026-02-02',
      course_fee: 40000,
      discount: 0,
      net_payable: 40000,
      payment_plan: '2 Installments',
      counsellor_id: 'usr-counsellor',
      counsellor_name: 'Ananya Desai',
      status: 'Confirmed',
      created_at: '2026-02-02T11:00:00Z',
      updated_at: '2026-02-02T11:00:00Z',
    },
  ];

  public students: Student[] = [
    {
      id: 'stu-01',
      user_id: 'usr-student-01',
      admission_id: 'adm-01',
      student_code: 'STU-FICO-001',
      admission_number: 'ADM-2026-0001',
      full_name: 'Amit Gupta',
      email: 'amit.gupta@student.next-gen.com',
      phone: '+91 98111 22233',
      address: 'H-12, Madhapur, Hyderabad',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      batch_id: 'batch-fico-01',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      trainer_id: 'usr-trainer-fico',
      trainer_name: 'Vikram Rao',
      joining_date: '2026-02-01',
      status: 'Active',
      total_fee: 40000,
      paid_amount: 25000,
      outstanding_amount: 15000,
      attendance_percentage: 92.5,
      course_progress: 68.0,
      placement_status: 'Resume Preparation',
      created_at: '2026-01-25T10:00:00Z',
      updated_at: '2026-01-25T10:00:00Z',
    },
    {
      id: 'stu-02',
      user_id: 'usr-student-02',
      admission_id: 'adm-02',
      student_code: 'STU-MM-002',
      admission_number: 'ADM-2026-0002',
      full_name: 'Sneha Kulkarni',
      email: 'sneha.k@student.next-gen.com',
      phone: '+91 98222 33344',
      address: '404 Baner Road, Pune',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      batch_id: 'batch-mm-01',
      batch_name: 'SAP MM Weekend Professional Batch',
      trainer_id: 'usr-trainer-mm',
      trainer_name: 'Neha Patel',
      joining_date: '2026-02-15',
      status: 'Active',
      total_fee: 40000,
      paid_amount: 20000,
      outstanding_amount: 20000,
      attendance_percentage: 88.0,
      course_progress: 52.0,
      placement_status: 'Not Started',
      created_at: '2026-02-02T11:00:00Z',
      updated_at: '2026-02-02T11:00:00Z',
    },
  ];

  public leads: Lead[] = [
    {
      id: 'lead-01',
      lead_code: 'LD-2026-001',
      full_name: 'Vikas Sharma',
      phone: '+91 99887 76655',
      email: 'vikas.sharma@gmail.com',
      interested_course_id: 'crs-fico-01',
      interested_course_name: 'SAP S/4HANA Finance (FICO)',
      current_status: 'Working as Accounts Executive (3 yrs)',
      experience_years: 3,
      training_preference: 'Hybrid',
      lead_source: 'Google Ads',
      campaign: 'FICO_S4HANA_Q1',
      counsellor_id: 'usr-counsellor',
      counsellor_name: 'Ananya Desai',
      demo_preference: true,
      demo_date: '2026-03-01T11:00:00Z',
      follow_up_date: '2026-03-02',
      notes: 'Wants to transition from Tally to SAP FICO consultant. Inquired about weekend vs weekday batches.',
      stage: 'Demo Scheduled',
      created_at: '2026-02-20T09:30:00Z',
      updated_at: '2026-02-20T09:30:00Z',
    },
    {
      id: 'lead-02',
      lead_code: 'LD-2026-002',
      full_name: 'Deepika Reddy',
      phone: '+91 98711 22334',
      email: 'deepika.r@gmail.com',
      interested_course_id: 'crs-mm-01',
      interested_course_name: 'SAP S/4HANA Materials Management (MM)',
      current_status: 'Supply Chain Fresher',
      experience_years: 0,
      training_preference: 'Classroom',
      lead_source: 'Walk-in',
      counsellor_id: 'usr-counsellor',
      counsellor_name: 'Ananya Desai',
      follow_up_date: '2026-03-05',
      notes: 'Interested in placement support and mock interview tracks.',
      stage: 'Interested',
      created_at: '2026-02-22T14:15:00Z',
      updated_at: '2026-02-22T14:15:00Z',
    },
    {
      id: 'lead-03',
      lead_code: 'LD-2026-003',
      full_name: 'Karthik Rao',
      phone: '+91 97654 32190',
      email: 'karthik.abap@gmail.com',
      interested_course_id: 'crs-abap-01',
      interested_course_name: 'SAP ABAP on HANA & RESTful Application Programming (RAP)',
      current_status: 'Java Developer',
      experience_years: 2,
      training_preference: 'Online',
      lead_source: 'Website',
      stage: 'New',
      created_at: '2026-02-26T16:00:00Z',
      updated_at: '2026-02-26T16:00:00Z',
    },
  ];

  public feeAccounts: StudentFeeAccount[] = [
    {
      id: 'fa-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_id: 'adm-01',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      original_fee: 45000,
      discount: 5000,
      discount_reason: 'Early bird registration discount',
      net_payable: 40000,
      paid_amount: 25000,
      outstanding_amount: 15000,
      payment_plan: '3 Installments',
      status: 'Partially Paid',
      created_at: '2026-01-25T10:00:00Z',
      updated_at: '2026-02-24T12:00:00Z',
    },
    {
      id: 'fa-02',
      student_id: 'stu-02',
      student_name: 'Sneha Kulkarni',
      admission_id: 'adm-02',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      original_fee: 40000,
      discount: 0,
      net_payable: 40000,
      paid_amount: 20000,
      outstanding_amount: 20000,
      payment_plan: '2 Installments',
      status: 'Partially Paid',
      created_at: '2026-02-02T11:00:00Z',
      updated_at: '2026-02-02T11:00:00Z',
    },
  ];

  public installments: Installment[] = [
    {
      id: 'inst-01-1',
      fee_account_id: 'fa-01',
      student_id: 'stu-01',
      installment_number: 1,
      amount: 15000,
      due_date: '2026-01-25',
      paid_amount: 15000,
      paid_date: '2026-01-25',
      status: 'Paid',
    },
    {
      id: 'inst-01-2',
      fee_account_id: 'fa-01',
      student_id: 'stu-01',
      installment_number: 2,
      amount: 10000,
      due_date: '2026-02-25',
      paid_amount: 10000,
      paid_date: '2026-02-24',
      status: 'Paid',
    },
    {
      id: 'inst-01-3',
      fee_account_id: 'fa-01',
      student_id: 'stu-01',
      installment_number: 3,
      amount: 15000,
      due_date: '2026-03-25',
      paid_amount: 0,
      status: 'Upcoming',
    },
    {
      id: 'inst-02-1',
      fee_account_id: 'fa-02',
      student_id: 'stu-02',
      installment_number: 1,
      amount: 20000,
      due_date: '2026-02-02',
      paid_amount: 20000,
      paid_date: '2026-02-02',
      status: 'Paid',
    },
    {
      id: 'inst-02-2',
      fee_account_id: 'fa-02',
      student_id: 'stu-02',
      installment_number: 2,
      amount: 20000,
      due_date: '2026-03-02',
      paid_amount: 0,
      status: 'Due',
    },
  ];

  public payments: Payment[] = [
    {
      id: 'pay-01',
      receipt_number: 'REC-2026-0001',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      fee_account_id: 'fa-01',
      installment_id: 'inst-01-1',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      amount: 15000,
      payment_date: '2026-01-25',
      payment_mode: 'UPI',
      transaction_reference: 'UPI/260125/4491028',
      collected_by: 'usr-accounts',
      collected_by_name: 'Suresh Kumar',
      notes: 'Initial admission installment',
      created_at: '2026-01-25T10:15:00Z',
    },
    {
      id: 'pay-02',
      receipt_number: 'REC-2026-0002',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      fee_account_id: 'fa-01',
      installment_id: 'inst-01-2',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      amount: 10000,
      payment_date: '2026-02-24',
      payment_mode: 'Bank Transfer',
      transaction_reference: 'NEFT-HDFC-991823',
      collected_by: 'usr-accounts',
      collected_by_name: 'Suresh Kumar',
      notes: 'Second installment clear',
      created_at: '2026-02-24T11:45:00Z',
    },
    {
      id: 'pay-03',
      receipt_number: 'REC-2026-0003',
      student_id: 'stu-02',
      student_name: 'Sneha Kulkarni',
      admission_number: 'ADM-2026-0002',
      fee_account_id: 'fa-02',
      installment_id: 'inst-02-1',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      amount: 20000,
      payment_date: '2026-02-02',
      payment_mode: 'UPI',
      transaction_reference: 'UPI/260202/882194',
      collected_by: 'usr-accounts',
      collected_by_name: 'Suresh Kumar',
      notes: 'First installment payment',
      created_at: '2026-02-02T11:20:00Z',
    },
  ];

  public receipts: Receipt[] = [
    {
      id: 'rcpt-01',
      receipt_number: 'REC-2026-0001',
      payment_id: 'pay-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      course_name: 'SAP S/4HANA Finance (FICO)',
      payment_amount: 15000,
      payment_mode: 'UPI',
      transaction_reference: 'UPI/260125/4491028',
      payment_date: '2026-01-25',
      remaining_balance: 25000,
      authorized_by: 'Suresh Kumar (Chief Accountant)',
      institute_name: 'Next-Gen ERP Solutions',
      institute_address: 'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad 500081',
      institute_phone: '+91 98765 43210',
      institute_gst: '36AAACN1234F1Z8',
      supply_type: 'INTRA_STATE',
      place_of_supply: 'Telangana (36)',
      place_of_supply_code: '36',
      sac_code: '999293',
      taxable_amount: 12711.86,
      cgst_rate: 9,
      cgst_amount: 1144.07,
      sgst_rate: 9,
      sgst_amount: 1144.07,
      igst_rate: 0,
      igst_amount: 0,
      total_tax: 2288.14,
      is_reverse_charge: false,
      irn: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ack_no: '1226102948191',
      ack_date: '2026-01-25T10:15:00Z',
      created_at: '2026-01-25T10:15:00Z',
    },
    {
      id: 'rcpt-02',
      receipt_number: 'REC-2026-0002',
      payment_id: 'pay-02',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      course_name: 'SAP S/4HANA Finance (FICO)',
      payment_amount: 10000,
      payment_mode: 'Bank Transfer',
      transaction_reference: 'NEFT-HDFC-991823',
      payment_date: '2026-02-24',
      remaining_balance: 15000,
      authorized_by: 'Suresh Kumar (Chief Accountant)',
      institute_name: 'Next-Gen ERP Solutions',
      institute_address: 'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad 500081',
      institute_phone: '+91 98765 43210',
      institute_gst: '36AAACN1234F1Z8',
      supply_type: 'INTRA_STATE',
      place_of_supply: 'Telangana (36)',
      place_of_supply_code: '36',
      sac_code: '999293',
      taxable_amount: 8474.58,
      cgst_rate: 9,
      cgst_amount: 762.71,
      sgst_rate: 9,
      sgst_amount: 762.71,
      igst_rate: 0,
      igst_amount: 0,
      total_tax: 1525.42,
      is_reverse_charge: false,
      irn: 'a4b1c23458fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b999',
      ack_no: '1226102948292',
      ack_date: '2026-02-24T11:45:00Z',
      created_at: '2026-02-24T11:45:00Z',
    },
    {
      id: 'rcpt-03',
      receipt_number: 'REC-2026-0003',
      payment_id: 'pay-03',
      student_id: 'stu-02',
      student_name: 'Sneha Kulkarni',
      admission_number: 'ADM-2026-0002',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      payment_amount: 20000,
      payment_mode: 'UPI',
      transaction_reference: 'UPI/260202/882194',
      payment_date: '2026-02-02',
      remaining_balance: 20000,
      authorized_by: 'Suresh Kumar (Chief Accountant)',
      institute_name: 'Next-Gen ERP Solutions',
      institute_address: 'Plot 42, Silicon Valley Towers, Hitec City, Hyderabad 500081',
      institute_phone: '+91 98765 43210',
      institute_gst: '36AAACN1234F1Z8',
      supply_type: 'INTER_STATE',
      place_of_supply: 'Maharashtra (27)',
      place_of_supply_code: '27',
      sac_code: '999293',
      taxable_amount: 16949.15,
      cgst_rate: 0,
      cgst_amount: 0,
      sgst_rate: 0,
      sgst_amount: 0,
      igst_rate: 18,
      igst_amount: 3050.85,
      total_tax: 3050.85,
      is_reverse_charge: false,
      irn: 'b7c2d34568fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b777',
      ack_no: '1226102948393',
      ack_date: '2026-02-02T11:20:00Z',
      created_at: '2026-02-02T11:20:00Z',
    },
  ];

  public vendors: Vendor[] = [
    {
      id: 'ven-01',
      vendor_name: 'Amazon Web Services India Pvt Ltd',
      contact_person: 'AWS Cloud Account Rep',
      phone: '+91 80 4000 1234',
      email: 'aws-billing@amazon.com',
      address: 'Bengaluru, Karnataka',
      gst_number: '29AABCA1234F1Z1',
      bank_name: 'Citibank N.A.',
      bank_account_number: '9827162541',
      bank_ifsc: 'CITI0000002',
      total_paid: 24500,
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'ven-02',
      vendor_name: 'Silicon Towers Facilities Management',
      contact_person: 'K. Ramesh',
      phone: '+91 94400 11223',
      email: 'facilities@silicontowers.com',
      address: 'Hitec City, Hyderabad',
      gst_number: '36AAAFS5566G1Z2',
      bank_name: 'State Bank of India',
      bank_account_number: '33182749102',
      bank_ifsc: 'SBIN0004123',
      total_paid: 150000,
      created_at: '2026-01-01T00:00:00Z',
    },
  ];

  public expenses: Expense[] = [
    {
      id: 'exp-01',
      expense_code: 'EXP-2026-001',
      expense_date: '2026-02-01',
      category: 'Rent',
      vendor_id: 'ven-02',
      vendor_name: 'Silicon Towers Facilities Management',
      description: 'Monthly Institute Premises & Lab Rent for Feb 2026',
      amount: 75000,
      payment_mode: 'Bank Transfer',
      reference: 'NEFT-RENT-FEB26',
      status: 'Paid',
      paid_by: 'usr-accounts',
      paid_by_name: 'Suresh Kumar',
      approved_by: 'usr-superadmin',
      approved_by_name: 'Rajesh Sharma',
      created_at: '2026-02-01T10:00:00Z',
      updated_at: '2026-02-01T10:00:00Z',
    },
    {
      id: 'exp-02',
      expense_code: 'EXP-2026-002',
      expense_date: '2026-02-05',
      category: 'Internet',
      vendor_id: 'ven-01',
      vendor_name: 'Amazon Web Services India Pvt Ltd',
      description: 'Dedicated Fiber Internet & Cloud Server Hosting',
      amount: 14500,
      payment_mode: 'Card',
      reference: 'TXN-AWS-FEB-26',
      status: 'Paid',
      paid_by: 'usr-accounts',
      approved_by: 'usr-superadmin',
      created_at: '2026-02-05T15:30:00Z',
      updated_at: '2026-02-05T15:30:00Z',
    },
    {
      id: 'exp-03',
      expense_code: 'EXP-2026-003',
      expense_date: '2026-02-28',
      category: 'Marketing',
      description: 'Meta & Google Ads Campaign for March SAP Batches',
      amount: 22000,
      payment_mode: 'Card',
      reference: 'FB-ADS-INV-9921',
      status: 'Paid',
      paid_by: 'usr-accounts',
      approved_by: 'usr-superadmin',
      created_at: '2026-02-28T09:00:00Z',
      updated_at: '2026-02-28T09:00:00Z',
    },
  ];

  public classSessions: ClassSession[] = [
    {
      id: 'sess-01',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      batch_id: 'batch-fico-01',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      trainer_id: 'usr-trainer-fico',
      trainer_name: 'Vikram Rao',
      topic: 'Financial Statement Version (FSV) & General Ledger Configuration',
      session_date: '2026-03-02',
      start_time: '08:00',
      end_time: '10:00',
      mode: 'Hybrid',
      meeting_link: 'https://meet.google.com/xyz-fico-sap',
      meeting_id: 'xyz-fico-sap',
      meeting_provider: 'Google Meet',
      classroom: 'Lab 2 (SAP S/4HANA Server Lab)',
      notes: 'Bring previous assignment blueprint printouts',
      status: 'Scheduled',
      created_at: '2026-02-25T10:00:00Z',
    },
    {
      id: 'sess-02',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      batch_id: 'batch-mm-01',
      batch_name: 'SAP MM Weekend Professional Batch',
      trainer_id: 'usr-trainer-mm',
      trainer_name: 'Neha Patel',
      topic: 'Purchase Requisition to Purchase Order Workflow & Pricing Schema',
      session_date: '2026-03-07',
      start_time: '10:00',
      end_time: '13:00',
      mode: 'Online',
      meeting_link: 'https://zoom.us/j/9876543210',
      meeting_id: '9876543210',
      meeting_provider: 'Zoom',
      status: 'Scheduled',
      created_at: '2026-02-25T10:00:00Z',
    },
  ];

  public meetingLogs: MeetingParticipantLog[] = [];

  public attendanceRecords: AttendanceRecord[] = [
    {
      id: 'att-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      batch_id: 'batch-fico-01',
      session_id: 'sess-01',
      attendance_date: '2026-02-27',
      status: 'Present',
      source: 'Google Meet',
      meeting_id: 'xyz-fico-sap',
      duration_minutes: 115,
      marked_by: 'usr-trainer-fico',
      marked_by_name: 'Vikram Rao',
      marked_at: '2026-02-27T08:15:00Z',
    },
  ];

  public assignments: Assignment[] = [
    {
      id: 'asg-01',
      title: 'Company Code & Chart of Accounts Configuration Exercise',
      description: 'Configure a new global enterprise model with 2 Company Codes, operational chart of accounts, and fiscal year variant K4 in the SAP sandbox.',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      batch_id: 'batch-fico-01',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      module_id: 'mod-fico-01',
      due_date: '2026-03-05T23:59:59Z',
      maximum_marks: 100,
      attachment_url: 'https://example.com/handouts/fico-asg1.pdf',
      created_by: 'usr-trainer-fico',
      created_at: '2026-02-20T10:00:00Z',
      submissions_count: 14,
    },
  ];

  public submissions: AssignmentSubmission[] = [
    {
      id: 'sub-01',
      assignment_id: 'asg-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      submission_text: 'Completed configuration for Company Code IN10 and US10 with Chart of Accounts CAIN. Screenshots and transport request logs attached.',
      submitted_at: '2026-02-26T18:30:00Z',
      status: 'Graded',
      marks_obtained: 95,
      feedback: 'Excellent configuration clarity. Posting period variant is correctly mapped.',
      graded_by: 'usr-trainer-fico',
      graded_at: '2026-02-27T14:00:00Z',
    },
  ];

  public quizzes: Quiz[] = [
    {
      id: 'quiz-01',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      title: 'SAP FICO Module 1 Certification Assessment',
      description: 'Assessment testing General Ledger concepts, Document Splitting, and S/4HANA ACDOCA table architecture.',
      duration_minutes: 45,
      pass_percentage: 70,
      attempts_allowed: 2,
      randomize_questions: true,
      show_answers_after: true,
      questions_count: 5,
      status: 'Published',
      created_at: '2026-02-15T10:00:00Z',
    },
  ];

  public quizQuestions: QuizQuestion[] = [
    {
      id: 'qq-01',
      quiz_id: 'quiz-01',
      question_text: 'Which table in SAP S/4HANA serves as the Universal Journal containing both FI and CO line items?',
      question_type: 'MCQ',
      points: 20,
      order_index: 1,
      options: [
        { id: 'opt-1', text: 'BSEG', is_correct: false },
        { id: 'opt-2', text: 'BKPF', is_correct: false },
        { id: 'opt-3', text: 'ACDOCA', is_correct: true },
        { id: 'opt-4', text: 'FAGLFLEXA', is_correct: false },
      ],
      explanation: 'ACDOCA is the Universal Journal table in SAP S/4HANA unifying general ledger, asset accounting, controlling, and profitability analysis.',
    },
    {
      id: 'qq-02',
      quiz_id: 'quiz-01',
      question_text: 'Is Business Partner (BP) mandatory for creating Customers and Vendors in SAP S/4HANA?',
      question_type: 'TrueFalse',
      points: 20,
      order_index: 2,
      options: [
        { id: 'opt-21', text: 'True', is_correct: true },
        { id: 'opt-22', text: 'False', is_correct: false },
      ],
      explanation: 'Yes, in S/4HANA, traditional transactions like XD01 and XK01 redirect to transaction BP (Business Partner).',
    },
  ];

  public quizAttempts: QuizAttempt[] = [
    {
      id: 'qa-01',
      quiz_id: 'quiz-01',
      quiz_title: 'SAP FICO Module 1 Certification Assessment',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      score: 40,
      total_points: 40,
      percentage: 100,
      passed: true,
      started_at: '2026-02-28T16:00:00Z',
      completed_at: '2026-02-28T16:25:00Z',
      status: 'Completed',
    },
  ];

  public placementProfiles: PlacementProfile[] = [
    {
      id: 'pp-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      resume_url: 'https://example.com/resumes/amit_gupta_fico.pdf',
      resume_status: 'Reviewed & Approved',
      mock_interview_status: 'Completed',
      technical_interview_score: 92,
      hr_interview_score: 88,
      skills: ['SAP FICO', 'S/4HANA New GL', 'Asset Accounting', 'F110', 'Dunning', 'B.Com / MBA'],
      experience_years: 2,
      preferred_location: 'Hyderabad / Bengaluru',
      expected_salary_lpa: 7.5,
      placement_status: 'Resume Preparation',
      created_at: '2026-02-10T10:00:00Z',
      updated_at: '2026-02-26T12:00:00Z',
    },
  ];

  public jobOpenings: JobOpening[] = [
    {
      id: 'job-01',
      company_name: 'Deloitte USI',
      job_title: 'SAP FICO Associate Consultant',
      module: 'SAP FICO',
      experience_required: '0 - 2 Years',
      location: 'Hyderabad / Bengaluru',
      salary_range: '₹6.5 - ₹8.5 LPA',
      description: 'Seeking trained SAP FICO consultants with solid grasp on General Ledger, Accounts Payable, Accounts Receivable, and Asset Accounting on S/4HANA.',
      application_deadline: '2026-04-30',
      status: 'Open',
      applications_count: 8,
      created_at: '2026-02-15T10:00:00Z',
    },
    {
      id: 'job-02',
      company_name: 'Accenture Solutions',
      job_title: 'SAP MM Functional Analyst',
      module: 'SAP MM',
      experience_required: '0 - 3 Years',
      location: 'Pune / Mumbai',
      salary_range: '₹6.0 - ₹8.0 LPA',
      description: 'Procure to pay lifecycle, master data governance, inventory control, and purchase order configuration.',
      application_deadline: '2026-05-15',
      status: 'Open',
      applications_count: 5,
      created_at: '2026-02-18T10:00:00Z',
    },
  ];

  public jobApplications: JobApplication[] = [
    {
      id: 'app-01',
      job_id: 'job-01',
      job_title: 'SAP FICO Associate Consultant',
      company_name: 'Deloitte USI',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      applied_at: '2026-02-25T14:00:00Z',
      status: 'Shortlisted',
      notes: 'Candidate profiled for Round 1 technical interview on March 10.',
    },
  ];

  public certificates: Certificate[] = [
    {
      id: 'cert-01',
      certificate_id: 'CERT-2026-FICO-0091',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      grade: 'A+ (Distinction)',
      issue_date: '2026-04-20',
      completion_date: '2026-04-18',
      attendance_percentage: 92.5,
      assignment_completion_rate: 95.0,
      exam_score_percentage: 91.0,
      verification_url: 'https://lms.next-generpsolutions.com/certificate/verify/CERT-2026-FICO-0091',
      is_valid: true,
      created_at: '2026-04-20T10:00:00Z',
    },
  ];

  public notifications: NotificationItem[] = [
    {
      id: 'notif-01',
      user_id: 'usr-student-01',
      title: 'Assignment Graded',
      message: 'Your assignment "Company Code & Chart of Accounts" scored 95/100.',
      type: 'success',
      category: 'assignment',
      is_read: false,
      action_url: '/portal',
      created_at: '2026-02-27T14:00:00Z',
    },
    {
      id: 'notif-02',
      user_id: 'usr-student-01',
      title: 'Upcoming Class Reminder',
      message: 'SAP FICO Live Lab Session scheduled for tomorrow at 08:00 AM.',
      type: 'info',
      category: 'class',
      is_read: false,
      action_url: '/portal',
      created_at: '2026-03-01T18:00:00Z',
    },
  ];

  public auditLogs: AuditLog[] = [
    {
      id: 'aud-01',
      user_id: 'usr-accounts',
      user_name: 'Suresh Kumar',
      user_role: 'accountant',
      action: 'PAYMENT_RECORDED',
      module: 'ACCOUNTS',
      record_id: 'pay-02',
      new_value: { amount: 10000, receipt: 'REC-2026-0002', student: 'Amit Gupta' },
      ip_address: '192.168.1.45',
      created_at: '2026-02-24T11:45:00Z',
    },
    {
      id: 'aud-02',
      user_id: 'usr-superadmin',
      user_name: 'Rajesh Sharma',
      user_role: 'super_admin',
      action: 'EXPENSE_APPROVED',
      module: 'FINANCE',
      record_id: 'exp-01',
      new_value: { amount: 75000, category: 'Rent', status: 'Approved' },
      ip_address: '192.168.1.10',
      created_at: '2026-02-01T10:05:00Z',
    },
  ];

  public sapSystems: SapServerSystem[] = [
    {
      id: 'sap-sys-01',
      system_name: 'SAP S/4HANA 2022 FPS02 Enterprise Sandbox',
      sid: 'S4H',
      instance_number: '00',
      server_host: 's4h.lab.next-generpsolutions.com',
      sap_router: '/H/103.212.120.45/S/3299',
      default_client: '800',
      description: 'Dedicated S/4HANA practice sandbox with full FICO, MM, SD, and ABAP customization tables.',
      status: 'Online',
    },
    {
      id: 'sap-sys-02',
      system_name: 'SAP ECC 6.0 EHP8 Production Simulation',
      sid: 'DEV',
      instance_number: '01',
      server_host: 'ecc.lab.next-generpsolutions.com',
      default_client: '100',
      description: 'Classic ECC environment for legacy interface, IDoc, and transaction code reference practice.',
      status: 'Online',
    },
  ];

  public sapAllocations: SapServerAllocation[] = [
    {
      id: 'alloc-01',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      system_id: 'sap-sys-01',
      system_name: 'SAP S/4HANA 2022 FPS02 Enterprise Sandbox',
      server_host: 's4h.lab.next-generpsolutions.com',
      sid: 'S4H',
      instance_number: '00',
      client_number: '800',
      sap_user_id: 'SAP_AMITG',
      sap_password: 'InitialPass#2026',
      valid_from: '2026-01-15',
      valid_to: '2026-05-15',
      status: 'Active',
      allocated_by: 'usr-admin',
      created_at: '2026-01-15T09:00:00Z',
      updated_at: '2026-01-15T09:00:00Z',
    },
  ];

  public doubts: StudentDoubt[] = [
    {
      id: 'dbt-01',
      ticket_number: 'DBT-2026-001',
      student_id: 'stu-01',
      student_name: 'Amit Gupta',
      admission_number: 'ADM-2026-0001',
      course_id: 'crs-fico-01',
      course_name: 'SAP S/4HANA Finance (FICO)',
      batch_id: 'batch-fico-01',
      batch_name: 'SAP FICO Morning Fast-Track Batch',
      assigned_to_id: 'usr-support-01',
      assigned_to_name: 'Ananya Deshmukh',
      assigned_to_role: 'support',
      title: 'Error F5151: Company code 1000 is not defined in transaction FB50',
      description: 'When I try to post a GL document in FB50 for company code 1000, the system displays error F5151 saying company code is not fully defined. I completed OX02 and OX16.',
      category: 'SAP Configuration',
      priority: 'High',
      status: 'In Progress',
      sap_tcode: 'FB50',
      messages: [
        {
          id: 'msg-01',
          doubt_id: 'dbt-01',
          sender_id: 'usr-student-01',
          sender_name: 'Amit Gupta',
          sender_role: 'student',
          message: 'When I try to post a GL document in FB50 for company code 1000, the system displays error F5151 saying company code is not fully defined. I completed OX02 and OX16.',
          created_at: '2026-02-28T09:30:00Z',
        },
        {
          id: 'msg-02',
          doubt_id: 'dbt-01',
          sender_id: 'usr-support-01',
          sender_name: 'Ananya Deshmukh (Support)',
          sender_role: 'support',
          message: 'Hi Amit, please check transaction OBY6 (Company Code Global Parameters) to ensure the fiscal year variant (e.g. V3) and chart of accounts (INT) are assigned to company code 1000. Also verify OB52 for open posting periods.',
          created_at: '2026-02-28T10:15:00Z',
        },
      ],
      created_at: '2026-02-28T09:30:00Z',
      updated_at: '2026-02-28T10:15:00Z',
    },
    {
      id: 'dbt-02',
      ticket_number: 'DBT-2026-002',
      student_id: 'stu-02',
      student_name: 'Sneha Kulkarni',
      admission_number: 'ADM-2026-0002',
      course_id: 'crs-mm-01',
      course_name: 'SAP S/4HANA Materials Management (MM)',
      batch_id: 'batch-mm-01',
      batch_name: 'SAP MM Weekend Professional Batch',
      assigned_to_id: 'usr-support-01',
      assigned_to_name: 'Ananya Deshmukh',
      assigned_to_role: 'support',
      title: 'Account Determination Error M8147 in MIRO Invoice Verification',
      description: 'I get error M8147 "No account is maintained for transaction WRX in chart of accounts INT" when simulating invoice verification in MIRO.',
      category: 'SAP Configuration',
      priority: 'Medium',
      status: 'Open',
      sap_tcode: 'MIRO',
      messages: [
        {
          id: 'msg-03',
          doubt_id: 'dbt-02',
          sender_id: 'usr-student-02',
          sender_name: 'Sneha Kulkarni',
          sender_role: 'student',
          message: 'I get error M8147 "No account is maintained for transaction WRX in chart of accounts INT" when simulating invoice verification in MIRO.',
          created_at: '2026-03-01T14:00:00Z',
        },
      ],
      created_at: '2026-03-01T14:00:00Z',
      updated_at: '2026-03-01T14:00:00Z',
    },
  ];
}

// Global Singleton to preserve state across Server Actions & Next.js API Routes in dev/preview
const globalForStore = globalThis as unknown as { instituteStore?: InstituteDataStore };

export const store = globalForStore.instituteStore ?? new InstituteDataStore();
if (process.env.NODE_ENV !== 'production') globalForStore.instituteStore = store;
